/* A parser generated by PackCC 3.1.0 */

#ifndef PCC_INCLUDED_KOTLIN_H
#define PCC_INCLUDED_KOTLIN_H

#line 30 "ctags/peg/kotlin_opt.peg"
struct parserCtx;
#line 9 "ctags/peg/kotlin.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct pkotlin_context_tag pkotlin_context_t;

pkotlin_context_t *pkotlin_create(struct parserCtx *auxil);
int pkotlin_parse(pkotlin_context_t *ctx, int *ret);
void pkotlin_destroy(pkotlin_context_t *ctx);

#ifdef __cplusplus
}
#endif

#endif /* !PCC_INCLUDED_KOTLIN_H */
