[Icon Theme]
Name=Tango
Comment=Tango Icon Theme
Inherits=gnome,crystalsvg
Directories=16x16/actions,24x24/actions,32x32/actions,48x48/actions,scalable/actions


[16x16/actions]
Size=16
Context=Actions
Type=Threshold

[24x24/actions]
Size=24
Context=Actions
Type=Threshold

[32x32/actions]
Size=32
Context=Actions
Type=Threshold

[48x48/actions]
Size=48
Context=Actions
Type=Threshold

[scalable/actions]
MinSize=1
Size=128
MaxSize=256
Context=Actions
Type=Scalable
