/* A packrat parser generated by PackCC 1.5.0 */

#ifndef PCC_INCLUDED___PEG_KOTLIN_H
#define PCC_INCLUDED___PEG_KOTLIN_H

struct parserCtx;
#ifdef __cplusplus
extern "C" {
#endif

typedef struct pkotlin_context_tag pkotlin_context_t;

pkotlin_context_t *pkotlin_create(struct parserCtx *auxil);
int pkotlin_parse(pkotlin_context_t *ctx, int *ret);
void pkotlin_destroy(pkotlin_context_t *ctx);

#ifdef __cplusplus
}
#endif

#endif /* !PCC_INCLUDED___PEG_KOTLIN_H */
