#!/bin/sh

set -e

export LC_ALL=C

DATE=${1:-now}

# update the files
sed -e '1s/([^)]*)/('"$(date -d "$DATE" +'%B %d, %Y')"')/' -i NEWS
sed -e '1s/^\(.TH "[^"]*" "[^"]*" "\)[^"]*\("\)/\1'"$(date -d "$DATE" +'%B %d, %Y')"'\2/' -i doc/geany.1.in
sed -e 's/^\(:Date: \).*$/\1'"$(date -d "$DATE" +'%Y-%m-%d')"'/' -i doc/geany.txt

# show commit message to use
cat <<EOF
Message for the commit, after you have checked the changes:
-----------------------------------------------------------

Set release date
EOF
